services:
  app_spazzatura:        # <--- Manca il nome del servizio
    build: .           # <--- Punto (.) indica che il Dockerfile è nella stessa cartella
    ports:
      - "53147:53147"  # <--- Mappa la porta dell'host a quella del container
    restart: always
    env_file:
      - .env
